/**
 * gen-trig.ts - build-time generator for the COMMITTED integer trig tables.
 *
 * The pure simulation (src/sim/**) is forbidden from calling Math.sin/cos/atan2
 * (see eslint.config.js). Instead it reads fixed-point lookup tables that are
 * generated ONCE here and committed to the repository as src/sim/trig-tables.ts.
 *
 * This script is the ONLY place Math.sin/Math.cos are permitted, and it never
 * runs at simulation time. Regenerate with `npm run gen:trig`.
 *
 * Fixed-point convention (shared with src/sim/trig.ts):
 *   - Angles are expressed as "brads" (binary radians): a full turn is
 *     TABLE_SIZE (2^ANGLE_BITS) steps. This lets the sim mask angles with & to
 *     wrap, avoiding any floating remainder.
 *   - sin/cos values are scaled by TRIG_ONE and stored as signed integers.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ANGLE_BITS = 12; // 4096 entries per full turn -> ~0.088 degrees resolution
const TABLE_SIZE = 1 << ANGLE_BITS; // 4096
const ANGLE_MASK = TABLE_SIZE - 1;
const TRIG_SHIFT = 15; // sin/cos scaled by 32768
const TRIG_ONE = 1 << TRIG_SHIFT; // 32768

const TWO_PI = Math.PI * 2;

function buildSinTable(): Int32Array {
  const table = new Int32Array(TABLE_SIZE);
  for (let i = 0; i < TABLE_SIZE; i++) {
    const angle = (i / TABLE_SIZE) * TWO_PI;
    // Math.sin is allowed here (generation time only). Round to nearest int.
    table[i] = Math.round(Math.sin(angle) * TRIG_ONE);
  }
  return table;
}

function formatTable(values: Int32Array): string {
  const parts: string[] = [];
  for (let i = 0; i < values.length; i += 16) {
    const row = Array.from(values.subarray(i, i + 16)).join(', ');
    parts.push('  ' + row + ',');
  }
  return parts.join('\n');
}

function main(): void {
  const sinTable = buildSinTable();

  const header = `/**
 * AUTO-GENERATED by scripts/gen-trig.ts - DO NOT EDIT BY HAND.
 * Regenerate with \`npm run gen:trig\`.
 *
 * Committed integer trig tables consumed by the pure simulation. See
 * scripts/gen-trig.ts and src/sim/trig.ts for the fixed-point conventions.
 */
/* eslint-disable */

export const ANGLE_BITS = ${ANGLE_BITS};
export const TRIG_TABLE_SIZE = ${TABLE_SIZE};
export const ANGLE_MASK = ${ANGLE_MASK};
export const TRIG_SHIFT = ${TRIG_SHIFT};
export const TRIG_ONE = ${TRIG_ONE};

/**
 * Sine lookup, indexed by angle in brads (0..${ANGLE_MASK}). Values are
 * Math.round(sin(theta) * ${TRIG_ONE}). Cosine reuses this table with a
 * quarter-turn phase offset (see src/sim/trig.ts).
 */
export const SIN_TABLE: readonly number[] = [
${formatTable(sinTable)}
];
`;

  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = join(here, '..', 'src', 'sim', 'trig-tables.ts');
  writeFileSync(outPath, header, 'utf8');
  console.log(`gen-trig: wrote ${sinTable.length} sine entries to ${outPath}`);
}

main();
