/**
 * Deterministic fixed-point trigonometry for the pure simulation.
 *
 * All angles are "brads" (binary radians): a full turn is TRIG_TABLE_SIZE
 * steps (2^ANGLE_BITS). Sine/cosine are read from the COMMITTED table in
 * trig-tables.ts (generated by scripts/gen-trig.ts) and returned as fixed-point
 * integers scaled by TRIG_ONE. atan2 is a closed-form rational approximation
 * that uses only + - * / and no Math.atan2, so it stays deterministic.
 *
 * This module MUST NOT call Math.sin/cos/tan/atan2 - enforced by ESLint.
 */

import { ANGLE_MASK, SIN_TABLE, TRIG_ONE, TRIG_TABLE_SIZE } from './trig-tables.js';

const QUARTER_TURN = TRIG_TABLE_SIZE >> 2;

/** Wrap an integer angle (brads) into [0, TRIG_TABLE_SIZE). */
export function wrapAngle(angleBrads: number): number {
  return Math.trunc(angleBrads) & ANGLE_MASK;
}

/** sin(angle) as fixed-point (scaled by TRIG_ONE). angle in brads. */
export function sinFx(angleBrads: number): number {
  // Non-null: index is masked into valid table range.
  return SIN_TABLE[wrapAngle(angleBrads)] as number;
}

/** cos(angle) as fixed-point (scaled by TRIG_ONE). angle in brads. */
export function cosFx(angleBrads: number): number {
  return SIN_TABLE[wrapAngle(angleBrads + QUARTER_TURN)] as number;
}

/** sin(angle) as a JS float in [-1, 1]. Convenience for float consumers. */
export function sin(angleBrads: number): number {
  return sinFx(angleBrads) / TRIG_ONE;
}

/** cos(angle) as a JS float in [-1, 1]. */
export function cos(angleBrads: number): number {
  return cosFx(angleBrads) / TRIG_ONE;
}

/**
 * Deterministic atan2 returning an angle in brads in [0, TRIG_TABLE_SIZE).
 *
 * Uses a well-known rational approximation of atan on the reduced range
 * |t| <= 1 (t = min/max of |y|,|x|), then reflects into the correct octant.
 * Only + - * / are used; no Math.atan2. Max error is well under one table
 * step, which is all the sim needs for aiming and pattern math.
 */
export function atan2Brads(y: number, x: number): number {
  if (x === 0 && y === 0) return 0;

  const ax = x < 0 ? -x : x;
  const ay = y < 0 ? -y : y;

  // atanUnit(t) approximates atan(t)/(pi/2) for t in [0,1], scaled to a quarter
  // turn (QUARTER_TURN brads). Coefficients from the classic minimax form
  //   atan(t) ~= (pi/4)*t - t*(|t|-1)*(0.2447 + 0.0663*|t|)
  const quarter = QUARTER_TURN;
  let angle: number;
  if (ax >= ay) {
    const t = ay / ax; // in [0,1]
    const atan = (0.7853981633974483 * t - t * (t - 1) * (0.2447 + 0.0663 * t)) / 1.5707963267948966;
    angle = atan * quarter; // first octant fraction of a quarter turn
  } else {
    const t = ax / ay; // in [0,1]
    const atan = (0.7853981633974483 * t - t * (t - 1) * (0.2447 + 0.0663 * t)) / 1.5707963267948966;
    angle = quarter - atan * quarter; // mirror across 45deg
  }

  // Now `angle` is the magnitude in the first quadrant [0, QUARTER_TURN].
  // Place into the correct quadrant using the signs of x and y.
  let result: number;
  if (x >= 0 && y >= 0) result = angle;
  else if (x < 0 && y >= 0) result = 2 * quarter - angle;
  else if (x < 0 && y < 0) result = 2 * quarter + angle;
  else result = 4 * quarter - angle;

  return wrapAngle(Math.round(result));
}

export { TRIG_ONE, TRIG_TABLE_SIZE };
